#!/usr/bin/env node
// build.mjs — bundle the interactive demos. Zero dependencies; needs only Node.
//
// Convention ("recipe"): any post that wants demos has a `demo/demo.src.js` (an
// ES module that imports from assets/demos-core.js and calls boot({...})). This
// script auto-discovers every such file, inlines the shared core, and writes a
// self-contained classic script `demo/demo.js` next to it. The post's
// index.html loads that single file with <script defer src="demo/demo.js"></script>.
//
//   node build.mjs          build all discovered demos
//   node build.mjs --check   verify wiring without writing (CI-friendly)
//
// Re-run after editing any demo.src.js or assets/demos-core.js.

import {
  readFileSync,
  writeFileSync,
  readdirSync,
  existsSync,
  statSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const POSTS = join(ROOT, "posts");
const CORE = join(ROOT, "assets", "demos-core.js");
const CHECK = process.argv.includes("--check");

const stripExports = (src) => src.replace(/^export\s+/gm, "");
const stripImports = (src) =>
  src.replace(
    /^[ \t]*import\s*\{[^}]*\}\s*from\s*['"][^'"]+['"];?[ \t]*\r?\n?/gm,
    "",
  );

function discover() {
  if (!existsSync(POSTS)) return [];
  return readdirSync(POSTS)
    .map((name) => ({ slug: name, dir: join(POSTS, name) }))
    .filter((p) => {
      try {
        return statSync(p.dir).isDirectory();
      } catch {
        return false;
      }
    })
    .filter((p) => existsSync(join(p.dir, "demo", "demo.src.js")));
}

function bundle(coreSrc, entrySrc) {
  const core = stripExports(coreSrc).trim();
  const entry = stripImports(entrySrc).trim();
  return (
    "// GENERATED by build.mjs — do not edit by hand.\n" +
    "// Edit demo.src.js (and assets/demos-core.js), then run: node build.mjs\n" +
    '(function () {\n"use strict";\n\n' +
    core +
    "\n\n/* ---- post demo ---- */\n\n" +
    entry +
    "\n\n})();\n"
  );
}

function checkWiring(posts) {
  // Cross-check: index.html placeholders, the <script> tag, and the source.
  const problems = [];
  for (const { slug, dir } of posts) {
    const htmlPath = join(dir, "index.html");
    if (!existsSync(htmlPath)) {
      problems.push(`${slug}: has demo.src.js but no index.html`);
      continue;
    }
    const html = readFileSync(htmlPath, "utf8");
    const ids = [...html.matchAll(/data-demo="([^"]+)"/g)].map((m) => m[1]);
    if (ids.length === 0)
      problems.push(`${slug}: index.html has no [data-demo] placeholder`);
    if (!/src="demo\/demo\.js"/.test(html))
      problems.push(`${slug}: index.html does not load demo/demo.js`);
    if (!/assets\/demos\.css/.test(html))
      problems.push(`${slug}: index.html does not link assets/demos.css`);
    const entry = readFileSync(join(dir, "demo", "demo.src.js"), "utf8");
    const registered = [
      ...entry.matchAll(/["']([\w-]+)["']\s*:\s*(?:\(|function|async)/g),
    ].map((m) => m[1]);
    for (const id of ids)
      if (!registered.includes(id))
        problems.push(
          `${slug}: placeholder "${id}" is not registered in demo.src.js`,
        );
  }
  return problems;
}

const posts = discover();
if (posts.length === 0) {
  console.log("No demos found (looked for posts/*/demo.src.js).");
  process.exit(0);
}

const coreSrc = readFileSync(CORE, "utf8");
const manifest = [];
for (const { slug, dir } of posts) {
  const entrySrc = readFileSync(join(dir, "demo", "demo.src.js"), "utf8");
  const ids = [
    ...entrySrc.matchAll(/["']([\w-]+)["']\s*:\s*(?:\(|function|async)/g),
  ].map((m) => m[1]);
  manifest.push({ slug, demos: ids });
  if (!CHECK) {
    const out = bundle(coreSrc, entrySrc);
    writeFileSync(join(dir, "demo", "demo.js"), out);
    console.log(
      `built  posts/${slug}/demo/demo.js   (${(out.length / 1024).toFixed(1)} KB, demos: ${ids.join(", ")})`,
    );
  }
}

if (!CHECK) {
  writeFileSync(
    join(ROOT, "demos.manifest.json"),
    JSON.stringify(
      { generated: new Date().toISOString(), posts: manifest },
      null,
      2,
    ) + "\n",
  );
  console.log(`\nmanifest: demos.manifest.json (${manifest.length} post(s))`);
}

const problems = checkWiring(posts);
if (problems.length) {
  console.error("\nwiring problems:");
  for (const p of problems) console.error("  - " + p);
  process.exit(1);
}
console.log(CHECK ? "check passed." : "done.");
