// GENERATED by build.mjs — do not edit by hand.
// Edit demo.src.js (and assets/demos-core.js), then run: node build.mjs
(function () {
"use strict";

// demos-core.js — shared library for the interactive post demos.
//
// Plain ES module. The build step (build.mjs) inlines this verbatim into each
// post's self-contained demo.js bundle, so the browser never loads this file
// directly. Keep it free of any TOP-LEVEL access to `document`/`window`, so it
// can also be imported in Node for unit testing (math lives here on purpose).

// ----------------------------------------------------------------------------
// Theme — identical palette to the site CSS and the matplotlib figures.
// ----------------------------------------------------------------------------
const theme = {
  bg: "#0e1116",
  panel: "#151a21",
  line: "#222a35",
  fg: "#d7dde6",
  muted: "#8a94a3",
  accent: "#4aa3ff",
  accent2: "#e0a458",
  green: "#2a9d8f",
  red: "#d1495b",
  purple: "#c792ea",
};

// ----------------------------------------------------------------------------
// Math — pure functions, all unit-tested from Node.
// ----------------------------------------------------------------------------
function clamp(v, lo, hi) {
  return v < lo ? lo : v > hi ? hi : v;
}

// Eigen-decomposition of a symmetric 2x2 matrix [[a,b],[b,c]]; l1 >= l2.
function eigSym2(a, b, c) {
  const tr = a + c;
  const disc = Math.sqrt(Math.max(0, (a - c) * (a - c) + 4 * b * b));
  const l1 = (tr + disc) / 2,
    l2 = (tr - disc) / 2;
  let v1;
  if (Math.abs(b) > 1e-12) {
    // eigenvector of l1: (b, l1 - a)
    const n = Math.hypot(b, l1 - a) || 1;
    v1 = [b / n, (l1 - a) / n];
  } else {
    v1 = a >= c ? [1, 0] : [0, 1];
  }
  const v2 = [-v1[1], v1[0]];
  return { l1, l2, v1, v2 };
}

// Eigenvalues of a symmetric n x n matrix via the cyclic Jacobi method.
// Returns eigenvalues sorted descending. Adequate for the small (k<=12) matrices here.
function jacobiEigvals(M) {
  const n = M.length;
  const A = M.map((row) => row.slice());
  for (let sweep = 0; sweep < 100; sweep++) {
    let off = 0;
    for (let p = 0; p < n; p++)
      for (let q = p + 1; q < n; q++) off += A[p][q] * A[p][q];
    if (off < 1e-18) break;
    for (let p = 0; p < n; p++) {
      for (let q = p + 1; q < n; q++) {
        if (Math.abs(A[p][q]) < 1e-300) continue;
        const tau = (A[q][q] - A[p][p]) / (2 * A[p][q]);
        const t =
          Math.sign(tau || 1) / (Math.abs(tau) + Math.sqrt(tau * tau + 1));
        const c = 1 / Math.sqrt(t * t + 1),
          s = t * c;
        for (let k = 0; k < n; k++) {
          const akp = A[k][p],
            akq = A[k][q];
          A[k][p] = c * akp - s * akq;
          A[k][q] = s * akp + c * akq;
        }
        for (let k = 0; k < n; k++) {
          const apk = A[p][k],
            aqk = A[q][k];
          A[p][k] = c * apk - s * aqk;
          A[q][k] = s * apk + c * aqk;
        }
      }
    }
  }
  return A.map((_, i) => A[i][i]).sort((x, y) => y - x);
}

// Covariance builders used by the matrix-completion demo.
function buildEquicorr(k, rho) {
  const M = [];
  for (let i = 0; i < k; i++) {
    M.push([]);
    for (let j = 0; j < k; j++) M[i].push(i === j ? 1 : rho);
  }
  return M;
}
function buildAR1(k, rho) {
  const M = [];
  for (let i = 0; i < k; i++) {
    M.push([]);
    for (let j = 0; j < k; j++) M[i].push(Math.pow(rho, Math.abs(i - j)));
  }
  return M;
}

// Quantized-Gaussian completion capacity C = S / H_joint at resolution Delta.
// Each direction with variance lam contributes max(0, 0.5*log2(2*pi*e*lam) - log2(Delta)) bits.
function quantizedCapacity(eigs, diagVars, Delta) {
  const bits = (lam) =>
    Math.max(
      0,
      0.5 * Math.log2(2 * Math.PI * Math.E * Math.max(lam, 1e-300)) -
        Math.log2(Delta),
    );
  const S = diagVars.reduce((acc, v) => acc + bits(v), 0);
  const Hj = eigs.reduce((acc, l) => acc + bits(l), 0);
  return Hj < 1e-12 ? Infinity : S / Hj;
}

// log-gamma (Lanczos) and the Beta density, for the MLE/MAP demo.
const LG_G = 7;
const LG_C = [
  0.99999999999980993, 676.5203681218851, -1259.1392167224028,
  771.32342877765313, -176.61502916214059, 12.507343278686905,
  -0.13857109526572012, 9.9843695780195716e-6, 1.5056327351493116e-7,
];
function logGamma(x) {
  if (x < 0.5)
    return Math.log(Math.PI / Math.sin(Math.PI * x)) - logGamma(1 - x);
  x -= 1;
  let a = LG_C[0];
  const t = x + LG_G + 0.5;
  for (let i = 1; i < LG_G + 2; i++) a += LG_C[i] / (x + i);
  return (
    0.5 * Math.log(2 * Math.PI) + (x + 0.5) * Math.log(t) - t + Math.log(a)
  );
}
function betaPdf(x, a, b) {
  if (x <= 0 || x >= 1) return 0;
  const logB = logGamma(a) + logGamma(b) - logGamma(a + b);
  return Math.exp((a - 1) * Math.log(x) + (b - 1) * Math.log(1 - x) - logB);
}

// ----------------------------------------------------------------------------
// Stage — a responsive HiDPI canvas with unified mouse/touch dragging and
// data<->pixel transforms. DOM access only happens inside the constructor/methods.
// ----------------------------------------------------------------------------
class Stage {
  constructor(host, opts = {}) {
    this.host = host;
    this.height = opts.height || 320;
    this.pad = Object.assign({ l: 44, r: 18, t: 16, b: 34 }, opts.pad || {});
    this.canvas = document.createElement("canvas");
    this.canvas.className = "demo-canvas";
    host.appendChild(this.canvas);
    this.ctx = this.canvas.getContext("2d");
    this.xdom = [0, 1];
    this.ydom = [0, 1];
    this.draggables = [];
    this._drag = null;
    this._draw = () => {};
    this.layout = opts.layout || null; // optional fn(stage) run on every resize (and the first paint)
    this.cssW = 600;
    this.cssH = this.height;
    this._bindPointer();
    if (typeof ResizeObserver !== "undefined") {
      this._ro = new ResizeObserver(() => this.resize());
      this._ro.observe(host);
    }
    this.resize();
  }
  get plotW() {
    return this.cssW - this.pad.l - this.pad.r;
  }
  get plotH() {
    return this.cssH - this.pad.t - this.pad.b;
  }
  setDomain(xdom, ydom) {
    this.xdom = xdom.slice();
    this.ydom = ydom.slice();
  }
  // Pick domains so one data unit is the same number of pixels on both axes.
  fitEqual(xhalf, cx = 0, cy = 0) {
    const sx = this.plotW / (2 * xhalf);
    const yhalf = this.plotH / (2 * sx);
    this.xdom = [cx - xhalf, cx + xhalf];
    this.ydom = [cy - yhalf, cy + yhalf];
  }
  px(x) {
    const [l, r] = this.xdom;
    return this.pad.l + ((x - l) / (r - l)) * this.plotW;
  }
  py(y) {
    const [b, t] = this.ydom;
    return this.pad.t + ((t - y) / (t - b)) * this.plotH;
  }
  ux(px) {
    const [l, r] = this.xdom;
    return l + ((px - this.pad.l) / this.plotW) * (r - l);
  }
  uy(py) {
    const [b, t] = this.ydom;
    return t - ((py - this.pad.t) / this.plotH) * (t - b);
  }
  resize() {
    const dpr = (typeof window !== "undefined" && window.devicePixelRatio) || 1;
    const w = this.host.clientWidth || this.cssW;
    this.cssW = w;
    this.cssH = this.height;
    this.canvas.width = Math.max(1, Math.round(w * dpr));
    this.canvas.height = Math.max(1, Math.round(this.height * dpr));
    this.canvas.style.width = w + "px";
    this.canvas.style.height = this.height + "px";
    this.ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    if (this.layout) this.layout(this);
    this.render();
  }
  onDraw(fn) {
    this._draw = fn;
    return this;
  }
  render() {
    const c = this.ctx;
    c.clearRect(0, 0, this.cssW, this.cssH);
    this._draw(c, this);
  }
  addDraggable(d) {
    this.draggables.push(d);
    return d;
  }
  _pos(e) {
    const r = this.canvas.getBoundingClientRect();
    return { x: e.clientX - r.left, y: e.clientY - r.top };
  }
  _bindPointer() {
    const c = this.canvas;
    c.addEventListener("pointerdown", (e) => {
      const p = this._pos(e);
      let best = null,
        bd = 1e9;
      for (const d of this.draggables) {
        const dist = Math.hypot(this.px(d.x()) - p.x, this.py(d.y()) - p.y);
        if (dist < (d.r || 16) && dist < bd) {
          bd = dist;
          best = d;
        }
      }
      if (best) {
        this._drag = best;
        try {
          c.setPointerCapture(e.pointerId);
        } catch (_) {}
        e.preventDefault();
      }
    });
    c.addEventListener("pointermove", (e) => {
      if (!this._drag) return;
      const p = this._pos(e);
      this._drag.move(this.ux(p.x), this.uy(p.y));
      this.render();
      e.preventDefault();
    });
    const up = (e) => {
      if (this._drag) {
        try {
          c.releasePointerCapture(e.pointerId);
        } catch (_) {}
        this._drag = null;
      }
    };
    c.addEventListener("pointerup", up);
    c.addEventListener("pointercancel", up);
  }
  // ---- drawing helpers ----
  grid(step = 1) {
    const c = this.ctx;
    c.save();
    c.strokeStyle = theme.line;
    c.lineWidth = 1;
    c.globalAlpha = 0.5;
    const [xl, xr] = this.xdom,
      [yb, yt] = this.ydom;
    for (let x = Math.ceil(xl / step) * step; x <= xr; x += step) {
      c.beginPath();
      c.moveTo(this.px(x), this.pad.t);
      c.lineTo(this.px(x), this.pad.t + this.plotH);
      c.stroke();
    }
    for (let y = Math.ceil(yb / step) * step; y <= yt; y += step) {
      c.beginPath();
      c.moveTo(this.pad.l, this.py(y));
      c.lineTo(this.pad.l + this.plotW, this.py(y));
      c.stroke();
    }
    c.restore();
  }
  axisX(y = 0, label) {
    const c = this.ctx;
    c.save();
    c.strokeStyle = theme.muted;
    c.lineWidth = 1;
    c.globalAlpha = 0.8;
    c.beginPath();
    c.moveTo(this.pad.l, this.py(y));
    c.lineTo(this.pad.l + this.plotW, this.py(y));
    c.stroke();
    if (label) {
      c.globalAlpha = 1;
      c.fillStyle = theme.muted;
      c.font = "11px monospace";
      c.textAlign = "right";
      c.fillText(label, this.pad.l + this.plotW, this.py(y) + 14);
    }
    c.restore();
  }
  path(fn, color, width = 2, dash = null) {
    const c = this.ctx;
    c.save();
    c.strokeStyle = color;
    c.lineWidth = width;
    if (dash) c.setLineDash(dash);
    c.beginPath();
    const [xl, xr] = this.xdom;
    let started = false;
    const N = 240;
    for (let i = 0; i <= N; i++) {
      const x = xl + (i / N) * (xr - xl);
      const y = fn(x);
      if (!isFinite(y)) {
        started = false;
        continue;
      }
      const X = this.px(x),
        Y = this.py(y);
      if (!started) {
        c.moveTo(X, Y);
        started = true;
      } else c.lineTo(X, Y);
    }
    c.stroke();
    c.restore();
  }
  dot(x, y, color, r = 5, ring = false) {
    const c = this.ctx;
    c.save();
    c.fillStyle = color;
    c.beginPath();
    c.arc(this.px(x), this.py(y), r, 0, 2 * Math.PI);
    c.fill();
    if (ring) {
      c.strokeStyle = theme.bg;
      c.lineWidth = 2;
      c.stroke();
    }
    c.restore();
  }
  segment(x0, y0, x1, y1, color, width = 1.4, dash = null) {
    const c = this.ctx;
    c.save();
    c.strokeStyle = color;
    c.lineWidth = width;
    if (dash) c.setLineDash(dash);
    c.beginPath();
    c.moveTo(this.px(x0), this.py(y0));
    c.lineTo(this.px(x1), this.py(y1));
    c.stroke();
    c.restore();
  }
  circleData(cx, cy, rdata, color, width = 1.4) {
    const c = this.ctx;
    const rpx = Math.abs(this.px(cx + rdata) - this.px(cx));
    c.save();
    c.strokeStyle = color;
    c.lineWidth = width;
    c.beginPath();
    c.arc(this.px(cx), this.py(cy), rpx, 0, 2 * Math.PI);
    c.stroke();
    c.restore();
  }
}

// ----------------------------------------------------------------------------
// Small DOM widget builders.
// ----------------------------------------------------------------------------
function el(tag, cls, parent) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (parent) parent.appendChild(n);
  return n;
}

function widget(root, { title, note } = {}) {
  root.classList.add("demo-built");
  const head = el("div", "demo-head", root);
  if (title) head.textContent = title;
  const stageHost = el("div", "demo-stagehost", root);
  const controls = el("div", "demo-controls", root);
  const readout = el("div", "demo-readout", root);
  if (note) {
    const n = el("div", "demo-note muted", root);
    n.textContent = note;
  }
  return { head, stageHost, controls, readout };
}

function slider(
  host,
  { label, min, max, value, step = 0.01, fmt = (v) => v.toFixed(2), onInput },
) {
  const wrap = el("label", "demo-slider", host);
  const row = el("div", "demo-srow", wrap);
  const lab = el("span", "demo-slabel", row);
  lab.textContent = label;
  const val = el("span", "demo-sval", row);
  val.textContent = fmt(value);
  const input = el("input", null, wrap);
  input.type = "range";
  input.min = min;
  input.max = max;
  input.step = step;
  input.value = value;
  input.addEventListener("input", () => {
    const v = parseFloat(input.value);
    val.textContent = fmt(v);
    onInput(v);
  });
  return {
    input,
    get: () => parseFloat(input.value),
    set: (v) => {
      input.value = v;
      val.textContent = fmt(v);
    },
  };
}

function button(host, label, onClick) {
  const b = el("button", "demo-btn", host);
  b.type = "button";
  b.textContent = label;
  b.addEventListener("click", onClick);
  return b;
}

function toggle(host, label, value, onChange) {
  const wrap = el("label", "demo-check", host);
  const input = el("input", null, wrap);
  input.type = "checkbox";
  input.checked = value;
  const span = el("span", null, wrap);
  span.textContent = label;
  input.addEventListener("change", () => onChange(input.checked));
  return {
    get: () => input.checked,
    set: (v) => {
      input.checked = v;
    },
  };
}

function segmented(host, options, value, onChange) {
  const wrap = el("div", "demo-seg", host);
  const btns = options.map((opt) => {
    const b = el("button", "demo-segbtn", wrap);
    b.type = "button";
    b.textContent = opt.label;
    if (opt.value === value) b.classList.add("on");
    b.addEventListener("click", () => {
      btns.forEach((x) => x.classList.remove("on"));
      b.classList.add("on");
      onChange(opt.value);
    });
    return b;
  });
  return wrap;
}

// ----------------------------------------------------------------------------
// boot — mount registered demos into their [data-demo] placeholders.
// No-ops outside a browser, so the module is safe to import in Node.
// ----------------------------------------------------------------------------
function boot(map) {
  if (typeof document === "undefined") return;
  const run = () => {
    document.querySelectorAll("[data-demo]").forEach((node) => {
      const id = node.getAttribute("data-demo");
      const factory = map[id];
      if (!factory) return;
      node.innerHTML = "";
      try {
        factory(node);
      } catch (err) {
        node.innerHTML =
          '<p class="demo-fallback">This interactive demo failed to load.</p>';
        if (typeof console !== "undefined")
          console.error("[demo " + id + "]", err);
      }
    });
  };
  if (document.readyState === "loading")
    document.addEventListener("DOMContentLoaded", run);
  else run();
}

/* ---- post demo ---- */

class RNG {
  constructor(seed = 1) { this.s = seed >>> 0; }
  next() { this.s = (1664525 * this.s + 1013904223) >>> 0; return this.s / 4294967296; }
  normal() { const u1 = Math.max(1e-12, this.next()); const u2 = this.next(); return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2); }
}
function nPdf(x, mu, sig) { sig = Math.max(1e-6, sig); const z = (x - mu) / sig; return Math.exp(-0.5 * z * z) / (Math.sqrt(2 * Math.PI) * sig); }
function cPdf(x, x0, g) { g = Math.max(1e-6, g); const z = (x - x0) / g; return 1 / (Math.PI * g * (1 + z * z)); }
function targetPdf(caseId, x) {
  if (caseId === "gaussian") return nPdf(x, 0.4, 1.15);
  if (caseId === "gaussian_mix") return 0.5 * nPdf(x, -2.2, 0.55) + 0.5 * nPdf(x, 2.0, 0.85);
  if (caseId === "cauchy") return cPdf(x, 0.15, 1.0);
  if (caseId === "failure_underfit") return 0.5 * nPdf(x, -2.4, 0.38) + 0.5 * nPdf(x, 2.4, 0.38);
  return 0.5 * nPdf(x, -2.0, 0.45) + 0.5 * nPdf(x, 2.2, 0.6);
}
function domain(caseId) { return caseId === "cauchy" ? [-10, 10] : [-6, 6]; }
function sampleTarget(caseId, n, rng) {
  const out = [];
  for (let i = 0; i < n; i++) {
    if (caseId === "gaussian") out.push(0.4 + 1.15 * rng.normal());
    else if (caseId === "gaussian_mix") out.push((rng.next() < 0.5 ? -2.2 + 0.55 * rng.normal() : 2.0 + 0.85 * rng.normal()));
    else if (caseId === "cauchy") { const u = Math.min(1 - 1e-4, Math.max(1e-4, rng.next())); out.push(0.15 + Math.tan(Math.PI * (u - 0.5))); }
    else if (caseId === "failure_underfit") out.push((rng.next() < 0.5 ? -2.4 : 2.4) + 0.38 * rng.normal());
    else out.push((rng.next() < 0.5 ? -2.0 + 0.45 * rng.normal() : 2.2 + 0.6 * rng.normal()));
  }
  return out;
}
function initModel(caseId) {
  if (caseId === "gaussian" || caseId === "failure_underfit") return { kind: "gaussian", mu: 0.0, logs: Math.log(1.9) };
  if (caseId === "cauchy") return { kind: "cauchy", loc: 1.1, logg: Math.log(1.9) };
  return { kind: "mix2", mu1: -0.6, mu2: 0.8, logs: Math.log(1.4) };
}
function modelPdf(th, x) {
  if (th.kind === "gaussian") return nPdf(x, th.mu, Math.exp(th.logs));
  if (th.kind === "cauchy") return cPdf(x, th.loc, Math.exp(th.logg));
  const sig = Math.exp(th.logs); return 0.5 * nPdf(x, th.mu1, sig) + 0.5 * nPdf(x, th.mu2, sig);
}
function sampleModel(th, m, rng) {
  const xs = new Array(m), meta = new Array(m);
  if (th.kind === "gaussian") { const sig = Math.exp(th.logs); for (let j = 0; j < m; j++) { const z = rng.normal(); xs[j] = th.mu + sig * z; meta[j] = { z }; } }
  else if (th.kind === "cauchy") { const g = Math.exp(th.logg); for (let j = 0; j < m; j++) { const u = Math.min(1 - 1e-4, Math.max(1e-4, rng.next())); const t = Math.tan(Math.PI * (u - 0.5)); xs[j] = th.loc + g * t; meta[j] = { t }; } }
  else { const sig = Math.exp(th.logs); for (let j = 0; j < m; j++) { const comp = rng.next() < 0.5 ? 0 : 1; const z = rng.normal(); xs[j] = (comp === 0 ? th.mu1 : th.mu2) + sig * z; meta[j] = { comp, z }; } }
  return { xs, meta };
}
function step(state) {
  const { theta, data, m, lr } = state; const rng = new RNG(state.seed++); const { xs, meta } = sampleModel(theta, m, rng);
  const assign = new Array(data.length); const grad = new Array(m).fill(0); let loss = 0;
  for (let i = 0; i < data.length; i++) { let best = 0, bestd = Infinity; for (let j = 0; j < m; j++) { const d = (data[i] - xs[j]) * (data[i] - xs[j]); if (d < bestd) { best = j; bestd = d; } } assign[i] = best; grad[best] += 2 * (xs[best] - data[i]) / data.length; loss += bestd / data.length; }
  if (theta.kind === "gaussian") { let gmu = 0, glogs = 0; for (let j = 0; j < m; j++) { gmu += grad[j]; glogs += grad[j] * (xs[j] - theta.mu); } theta.mu -= lr * gmu; theta.logs = Math.max(Math.log(0.1), Math.min(Math.log(4), theta.logs - lr * glogs)); }
  else if (theta.kind === "cauchy") { let gloc = 0, glogg = 0; for (let j = 0; j < m; j++) { gloc += grad[j]; glogg += grad[j] * (xs[j] - theta.loc); } theta.loc -= lr * gloc; theta.logg = Math.max(Math.log(0.12), Math.min(Math.log(5), theta.logg - lr * glogg)); }
  else { let g1 = 0, g2 = 0, glogs = 0; for (let j = 0; j < m; j++) { if (meta[j].comp === 0) g1 += grad[j]; else g2 += grad[j]; const mu = meta[j].comp === 0 ? theta.mu1 : theta.mu2; glogs += grad[j] * (xs[j] - mu); } theta.mu1 -= lr * g1; theta.mu2 -= lr * g2; if (theta.mu1 > theta.mu2) { const t = theta.mu1; theta.mu1 = theta.mu2; theta.mu2 = t; } theta.logs = Math.max(Math.log(0.12), Math.min(Math.log(4), theta.logs - lr * glogs)); }
  state.last = { xs, assign, loss }; state.loss = loss;
}
function summary(th) { if (th.kind === "gaussian") return `μ=${th.mu.toFixed(2)}, σ=${Math.exp(th.logs).toFixed(2)}`; if (th.kind === "cauchy") return `x₀=${th.loc.toFixed(2)}, γ=${Math.exp(th.logg).toFixed(2)}`; return `μ₁=${th.mu1.toFixed(2)}, μ₂=${th.mu2.toFixed(2)}, σ=${Math.exp(th.logs).toFixed(2)}`; }
function drawDensity(stage, c, fn, color, xlo, xhi, lw = 2, dash = []) { c.save(); c.strokeStyle = color; c.lineWidth = lw; c.setLineDash(dash); c.beginPath(); const N = 240; for (let k = 0; k <= N; k++) { const x = xlo + (xhi - xlo) * k / N; const y = fn(x); const px = stage.px(x), py = stage.py(y); if (k === 0) c.moveTo(px, py); else c.lineTo(px, py); } c.stroke(); c.restore(); }
function drawRug(stage, c, xs, y, color) { c.save(); c.strokeStyle = color; c.lineWidth = 1.2; c.globalAlpha = 0.75; xs.forEach((x) => { const px = stage.px(x), py = stage.py(y); c.beginPath(); c.moveTo(px, py - 4); c.lineTo(px, py + 4); c.stroke(); }); c.restore(); }

function makeTrainer(root, mode) {
  const title = mode === "geom" ? "Geometry of the IMLE loss" : mode === "train" ? "Synthetic IMLE trainer" : "Failure lab";
  const note = mode === "geom" ? "Each data point claims its nearest sampled neighbor." : mode === "train" ? "Dashed curve = target density, blue curve = current model density." : "Under-capacity versus under-sampling.";
  const { stageHost, controls, readout } = widget(root, { title, note });
  let caseId = mode === "geom" ? "gaussian_mix" : mode === "train" ? "gaussian" : "failure_underfit";
  const mk = () => ({ caseId, data: sampleTarget(caseId, 96, new RNG(200 + caseId.length)), theta: initModel(caseId), m: caseId === "failure_few_samples" ? 16 : 96, lr: 0.06, seed: 700, last: null, loss: null });
  let state = mk();
  const stage = new Stage(stageHost, { height: 350, pad: { l: 44, r: 16, t: 16, b: 34 } });
  stage.onDraw((c, s) => {
    const [xlo, xhi] = domain(caseId); let ymax = 0;
    for (let k = 0; k <= 320; k++) { const x = xlo + (xhi - xlo) * k / 320; ymax = Math.max(ymax, targetPdf(caseId, x), modelPdf(state.theta, x)); }
    if (mode === "geom") {
      s.setDomain([xlo, xhi], [0, 1]); c.clearRect(0,0,s.cssW,s.cssH);
      c.strokeStyle = theme.line; c.lineWidth = 1; c.beginPath(); c.moveTo(s.pad.l, s.py(0.15)); c.lineTo(s.pad.l + s.plotW, s.py(0.15)); c.stroke(); c.beginPath(); c.moveTo(s.pad.l, s.py(0.85)); c.lineTo(s.pad.l + s.plotW, s.py(0.85)); c.stroke();
      c.fillStyle = theme.muted; c.font = "12px JetBrains Mono"; c.fillText("model samples", s.pad.l + 6, s.py(0.15) - 8); c.fillText("data", s.pad.l + 6, s.py(0.85) - 8);
      drawRug(s, c, state.data, 0.85, theme.accent2); if (state.last) { for (let q = 0; q < 24; q++) { const i = Math.floor((state.data.length - 1) * q / 23); const j = state.last.assign[i]; c.save(); c.strokeStyle = theme.purple; c.globalAlpha = 0.45; c.beginPath(); c.moveTo(s.px(state.data[i]), s.py(0.85)); c.lineTo(s.px(state.last.xs[j]), s.py(0.15)); c.stroke(); c.restore(); } drawRug(s, c, state.last.xs, 0.15, theme.accent); }
      else drawRug(s, c, sampleModel(state.theta, state.m, new RNG(12)).xs, 0.15, theme.accent);
    } else {
      s.setDomain([xlo, xhi], [-0.08, ymax * 1.2]); s.grid(0.25); s.axisX(0, "x");
      drawDensity(s, c, (x) => targetPdf(caseId, x), theme.muted, xlo, xhi, 1.8, [4, 4]); drawDensity(s, c, (x) => modelPdf(state.theta, x), theme.accent, xlo, xhi, 2.3, []);
      drawRug(s, c, state.data, -0.02, theme.accent2); if (state.last) drawRug(s, c, state.last.xs, -0.055, theme.green);
    }
  });
  const redraw = () => { readout.innerHTML = state.loss == null ? `${summary(state.theta)} · no update yet` : `${summary(state.theta)} &nbsp;·&nbsp; latest loss = <b>${state.loss.toFixed(3)}</b>`; stage.render(); };
  const doSteps = (n) => { for (let i = 0; i < n; i++) step(state); redraw(); };
  const cases = mode === "train" ? [{label:"gaussian",value:"gaussian"},{label:"gaussian sum",value:"gaussian_mix"},{label:"cauchy",value:"cauchy"}] : mode === "geom" ? [{label:"gaussian",value:"gaussian"},{label:"gaussian sum",value:"gaussian_mix"},{label:"cauchy",value:"cauchy"}] : [{label:"underfit family",value:"failure_underfit"},{label:"few samples",value:"failure_few_samples"}];
  segmented(controls, cases, caseId, (v) => { caseId = v; state = mk(); redraw(); });
  button(controls, mode === "geom" ? "sample + assign" : "step", () => doSteps(1));
  if (mode !== "geom") button(controls, "+10 steps", () => doSteps(10));
  button(controls, "reset", () => { state = mk(); redraw(); });
  if (mode !== "fail") slider(controls, { label: "model samples m", min: 12, max: 160, step: 4, value: state.m, fmt: (v) => `${v|0}`, onInput: (v) => { state.m = v|0; redraw(); } });
  if (mode === "train") slider(controls, { label: "learning rate", min: 0.01, max: 0.12, step: 0.005, value: state.lr, fmt: (v) => v.toFixed(3), onInput: (v) => { state.lr = v; } });
  redraw();
}

boot({ "imle-geometry": (root) => makeTrainer(root, "geom"), "imle-trainer": (root) => makeTrainer(root, "train"), "imle-failures": (root) => makeTrainer(root, "fail") });

})();
